ame: test && Build 

on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Build"
      
  Trivy:
    runs-on: ubuntu-latest
    needs: Build    
    steps:
    - name: Trivy
      run: echo "Trivy"
      
  Sonar:
    runs-on: ubuntu-latest
    needs: Build    
    steps:
    - name: Sonar
      run: echo "Sonar"
      
  Mvn:
    runs-on: ubuntu-latest
    needs: Build    
    steps:
    - name: Mvn
      run: echo "Mvn"