name: "Beta release"

on:
    push:
        branches:
            - main
    
    workflow_dispatch:
        inputs:
          environment:
            description: "Environment"
            type: environment
            required: true
jobs:
    create_release:
        runs-on: ubuntu-latest
        
        strategy:
          matrix:
            environment: [int, stg, ppd, prd]
        
        steps:
          - name: Release 
            if: ${{ inputs.environment == 'int' || inputs.environment == 'stg' }}
            run: echo ${{ matrix.environment }}
 
