name:  Manual Deployment 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'staging'
          
          
jobs:
  build-and-deploy:
    name: test_${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment ${{ inputs.environment }}
        run: echo "Environment ${{ inputs.environment }} "
      
