name:  Manual Deployment

on:
  workflow_dispatch:
    inputs:     
      environment:
        description: 'Environment to run tests against'
        type: choice
        options: 
          - int
          - stg
          - ppd
      build:
        type: boolean
        default: true
          
          
jobs:
  Sonar:
    if: ${{ github.event.inputs.build == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Sonar
      run: echo "Sonar"
      
  Mvn:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build == 'true' }}
    steps:
    - name: Mvn
      run: echo "Mvn"
      
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build == 'true' }}
    needs:
      - Mvn
      - Sonar
    steps:
    - name: Build
      run: echo "Build"
      
  Trivy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build == 'true' }}  
    needs: Build
    steps:
    - name: Trivy
      run: echo "Trivy"
      
  Deploy:
    name: deploy ${{ inputs.environment }}
    needs: ${{ github.event.inputs.build == 'false' || "trivy" }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Integration and Staging
      run: |
        echo "Deploy to ${{ inputs.environment }}"
        
