name: "Beta release"

on:
    push:
        branches:
            - main
    
    workflow_dispatch:
        inputs:
          environment:
            description: "Environment"
            type: environment
            required: true
    workflow_call:
        inputs:
          environment:
            description: Environment
            type: string
            required: true
            
jobs:
    create_release:
        runs-on: ubuntu-latest
        
        strategy:
          matrix:
            environment: [int, stg, ppd, prd]
        
        steps:
          - name: Release 
            if: ${{ github.event_name == 'workflow_dispatch' }}
            run: echo ${{ matrix.environment }}
            
          - name: Release 2
            run: echo "lkdlzkenvlzknvlkz ${{ matrix.environment }}"
