name:  Manual Deployment ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'staging'
          
          
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: echo "Environment: ${{ inputs.environment }}"
      
