name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [WORKERS, WEBSERVERS, SQSWORKERS]
        include:
          - service: middle-ledgers-loader
            type: WORKERS
          - service: ledgers-wallets-loaderv2
            type: WORKERS
      


          
            

    steps:
    - name: Build
      run: echo  ${{ matrix.type }} ${{ matrix.service }} ${{ matrix.env }} 
    
