name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [ test, test2 ]
        include:
          - component: WORKERS

    steps:
    - name: Build
      run: echo  ${{ matrix.component }}- ${{ matrix.suffix }}
      
      
