name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [WORKERS]
        service: [-middle-ledgers-loader,-ledgers-wallets-loaderv2,-ledgers-transactions-loaderv2,-ledgers-ledgers-loaderv2]
        include:
          - type: WEBSERVERS
            service: -ledgers
          - type: SQSWORKERS
            service: -ledgers            
        env: [int, ppd]
                    
            

    steps:
    - name: Build
      run: echo  ${{ matrix.type }} ${{ matrix.service }} ${{ matrix.env }} 
    
