name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prd]
        component: [ WEBSERVERS, SQSWORKERS,WORKERS ]
        suffix: ["-middle-ledgers-loader","-ledgers-wallets-loaderv2","-ledgers-transactions-loaderv2","-ledgers-ledgers-loaderv2"]
        exclude:
          - component: WEBSERVERS
            suffix: "-middle-ledgers-loader"
          - component: WEBSERVERS
            suffix: "-ledgers-wallets-loaderv2"
          - component: WEBSERVERS
            suffix: "-ledgers-transactions-loaderv2"   
          - component: WEBSERVERS
            suffix: "-ledgers-ledgers-loaderv2"              


          
            

    steps:
    - name: Build
      run: echo  ${{ matrix.component }} ${{ matrix.suffix }} ${{ matrix.env }} 
    
