name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [WORKERS, WEBSERVERS, SQSWORKERS]
        service: [middle-ledgers-loader, ledgers-wallets-loaderv2, ledgers-transactions-loaderv2, ledgers-ledgers-loaderv2, ledgers]
        include:
          - type: WORKERS
            service: middle-ledgers-loader
          - type: WORKERS
            service: ledgers-wallets-loaderv2
          - type: WORKERS
            service: ledgers-transactions-loaderv2
          - type: WORKERS
            service: ledgers-ledgers-loaderv2
          - type: WEBSERVERS
            service: ledgers
          - type: SQSWORKERS
            service: ledgers            


          
            

    steps:
    - name: Build
      run: echo  ${{ matrix.component }} ${{ matrix.suffix }} ${{ matrix.env }} 
    
