name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ dev, prd]
        component: [ WEBSERVERS, SQSWORKERS ]
        include:
          - component: WORKERS
            suffix: "-middle-ledgers-loader"
          - component: WORKERS
            suffix: "-ledgers-wallets-loaderv2"
          - component: WORKERS
            suffix: "-ledgers-transactions-loaderv2"   
          - component: WORKERS
            suffix: "-ledgers-ledgers-loaderv2"              


          
            

    steps:
    - name: Build
      run: echo  ${{ matrix.component }}- ${{ matrix.suffix }}
    
