name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ int, stg-approval ]
        include:
          # WORKERS combinations
          - component: WORKERS
            suffix: ledgers-wallets-loaderv2
          - component: WORKERS
            suffix: ledgers-transactions-loaderv2
          - component: WORKERS
            suffix: ledgers-ledgers-loaderv2
          - component: WORKERS
            suffix: ledgers-wallets-loaderv2
          - component: WORKERS
            suffix: ledgers-transactions-loaderv2
          - component: WORKERS
            suffix: ledgers-ledgers-loaderv2
          # WEBSERVERS combinations
          - component: WEBSERVERS
            suffix: ledgers
          # SQSWORKERS combinations
          - component: SQSWORKERS
            suffix: ledgers

        

                    
            

    steps:
    - name: Build
      run: echo  ${{ matrix.environment }} ${{ matrix.component }} ${{ matrix.suffix }} 
    
