name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ WORKERS, WEBSERVERS, SQSWORKERS ]
        suffix: [-middle-ledgers-loader,-ledgers-wallets-loaderv2,-ledgers-transactions-loaderv2,-ledgers-ledgers-loaderv2]
            

    steps:
    - name: Build
      run: echo  ${{ matrix.component }}- ${{ matrix.suffix }}
    
