name: Docker Build & Deploy

on:      
  push


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ WEBSERVERS, WORKERS ]
        include:
          - component: WORKERS
            suffix: test
                steps:
    - name: Build
      run: echo  ${{ matrix.component }}- ${{ matrix.suffix }}
      
      
